---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flask-app
  targetNamespace: final
